#!/usr/bin/env bash
# Copy the proprietary module implementations from the sibling
# nestbrain-modules checkout into this working tree. The private repo groups
# files by module (modules/<name>/...); inside each module the layout mirrors
# this monorepo, so the overlay is a plain copy. Desktop impl lands in a
# gitignored dir; web impls OVERWRITE tracked stub files, so those are marked
# skip-worktree to keep `git status` clean. Undo: scripts/unsync-modules.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/../nestbrain-modules"
[ -d "$SRC/modules" ] || { echo "nestbrain-modules not found at $SRC" >&2; exit 1; }

IDS=()
for mod in "$SRC"/modules/*/; do
  [ -d "$mod" ] || continue
  id="$(basename "$mod")"
  echo "  overlay: $id"
  # NO -t: synced files must get a FRESH mtime, otherwise next dev's file
  # watcher (mtime-based) never recompiles them and serves stale code.
  rsync -rlpgoD "$mod" "$ROOT/"
  IDS+=("\"$id\"")
done

# Authoritative built-in set for this overlay (read by dev-module.ts).
GEN="$ROOT/apps/desktop/src/built-in-modules.generated.ts"
{
  echo "// AUTO-GENERATED by the modules overlay — do not edit, do not commit."
  printf 'export const BUILT_IN: string[] = [%s];\n' "$(IFS=,; echo "${IDS[*]}")"
} > "$GEN"

cd "$ROOT"
STUBS=(
  apps/web/src/lib/module-settings.tsx
  apps/web/src/lib/terminal-context.tsx
  apps/web/src/lib/git-status-context.tsx
  apps/web/src/components/terminal-panel.tsx
  apps/web/src/components/branch-indicator.tsx
  apps/web/src/components/new-project-modal.tsx
  apps/web/src/components/project-filter.tsx
)
for f in "${STUBS[@]}"; do git update-index --skip-worktree "$f"; done
echo "✅ modules synced (per-module overlay; stubs marked skip-worktree)"
